server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_microservice
    username: emazon
    password: stock123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

appDescription: "Category API"
appVersion: "1.0.0"




